### ISSUE TITLE
Bone rotations about z-axis are inverted

### ISSUE THREAD

**Issue by connorrein** [unnamed/hephaestus-engine#28]
Left horn should have a rotation of +22.5 degrees on the $z$-axis as shown in Blockbench, but appears to have a rotation of -22.5 degrees in game.
![image](https://github.com/unnamed/hephaestus-engine/assets/43483846/2085519a-2db5-4fff-9c70-604aeaae98af)
![2024-02-28_01 14 37](https://github.com/unnamed/hephaestus-engine/assets/43483846/fb5f770a-80f0-4fc8-abfe-3d26d95ddd93)

**Comment by yusshu** [comment]
Reproduced, fix in progress

**Comment by yusshu** [comment]
Fixed on latest commit
