### ISSUE TITLE
Models are not rotated / positioned properly

### ISSUE THREAD

**Issue by Argedon** [unnamed/hephaestus-engine#6]
How it looks: https://youtu.be/jbRZa3N9Xps
How it should looks like: https://youtu.be/5bQz22d55Hw

To reproduce it you can just use Server located in minestom-runtime test package. 
If u want to use model showed in video, i can send u it in private message.

**Comment by yusshu** [comment]
Solved, should work now (version `0.4.0-SNAPSHOT`) 👍🏽 
Thanks.
